pub mod fetch;
pub mod validation;

use crate::modules::types::AppError;

// Re-export all items (includes __cmd__ and __specta__fn__ generated by proc macros)
pub use fetch::*;
pub use validation::*;

/// Map yt-dlp stderr output to a user-friendly AppError.
/// Shared by fetch_video_info and fetch_playlist_info.
fn map_stderr_error(stderr: &str) -> AppError {
    if stderr.contains("Private video") || stderr.contains("Sign in") {
        return AppError::MetadataError("비공개 비디오입니다. 접근할 수 없습니다.".to_string());
    }
    if stderr.contains("Video unavailable") || stderr.contains("not available") {
        return AppError::MetadataError("이 비디오는 사용할 수 없습니다.".to_string());
    }
    if stderr.contains("is not a valid URL") || stderr.contains("Unsupported URL") {
        return AppError::InvalidUrl("지원하지 않는 URL 형식입니다.".to_string());
    }
    if stderr.contains("HTTP Error 429") || stderr.contains("Too Many Requests") {
        return AppError::NetworkError(
            "요청이 너무 많습니다. 잠시 후 다시 시도하세요.".to_string(),
        );
    }
    if stderr.contains("No video formats found") {
        return AppError::MetadataError(
            "비디오 형식을 찾을 수 없습니다. 라이브 스트림일 수 있습니다.".to_string(),
        );
    }
    if stderr.contains("age") || stderr.contains("confirm your age") {
        return AppError::MetadataError(
            "연령 제한 콘텐츠입니다. 설정에서 쿠키 브라우저를 설정하세요.".to_string(),
        );
    }
    if stderr.contains("Could not copy") && stderr.contains("cookie") {
        return AppError::MetadataError(
            "브라우저 쿠키에 접근할 수 없습니다. 브라우저를 완전히 종료하거나, Firefox 쿠키를 사용하세요.".to_string(),
        );
    }

    AppError::MetadataError(format!(
        "yt-dlp 오류: {}",
        stderr.lines().last().unwrap_or(stderr)
    ))
}
